services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Leuchtfeuer\Mautic\:
    resource: '../Classes/*'

  Leuchtfeuer\Mautic\Hooks\MauticFormHook:
    public: true

  Leuchtfeuer\Mautic\EventListener\SynchronizeMauticData:
    tags:
      - name: event.listener
        identifier: synchronizeMauticData
        event: TYPO3\CMS\Backend\Controller\Event\AfterFormEnginePageInitializedEvent
